/*
 * Caculator.java
 *
 * Created on __DATE__, __TIME__
 */

package SimpleFactory;


/**
 *
 * @author  __USER__
 */
public class Caculator extends javax.swing.JFrame {

	/** Creates new form Caculator */
	public Caculator() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		caculateJButton = new javax.swing.JButton();
		clearJButton = new javax.swing.JButton();
		numAJlabel = new javax.swing.JLabel();
		numBJlabel = new javax.swing.JLabel();
		numAJTextField = new javax.swing.JTextField();
		numBJTextField = new javax.swing.JTextField();
		answerJLabel = new javax.swing.JLabel();
		resultJLabel = new javax.swing.JLabel();
		operJTextField = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		caculateJButton.setText("caculate");
		caculateJButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				caculateJButtonMouseClicked(evt);
			}
		});

		clearJButton.setText("clear");
		clearJButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				clearJButtonMouseClicked(evt);
			}
		});

		numAJlabel.setText("number A:");

		numBJlabel.setText("number B:");

		answerJLabel.setText("result:");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(39, 39, 39)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(numAJlabel).add(
																numBJlabel)
														.add(answerJLabel))
										.add(24, 24, 24)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																operJTextField,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																96,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																resultJLabel,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																96,
																Short.MAX_VALUE)
														.add(
																org.jdesktop.layout.GroupLayout.LEADING,
																layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING,
																				false)
																		.add(
																				numBJTextField)
																		.add(
																				numAJTextField,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				96,
																				Short.MAX_VALUE)))
										.add(75, 75, 75)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.TRAILING,
																false)
														.add(
																clearJButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.add(
																caculateJButton,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.add(31, 31, 31)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								layout
										.createSequentialGroup()
										.add(46, 46, 46)
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(numAJlabel)
														.add(
																numAJTextField,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(
												layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				35,
																				35,
																				35)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								numBJlabel)
																						.add(
																								numBJTextField,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																		.add(
																				29,
																				29,
																				29)
																		.add(
																				layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(
																								answerJLabel)
																						.add(
																								resultJLabel,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																								15,
																								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
														.add(
																layout
																		.createSequentialGroup()
																		.add(
																				2,
																				2,
																				2)
																		.add(
																				caculateJButton)
																		.add(
																				36,
																				36,
																				36)
																		.add(
																				clearJButton)))
										.add(57, 57, 57)
										.add(
												operJTextField,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(58, Short.MAX_VALUE)));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	//GEN-FIRST:event_caculateJButtonMouseClicked
	private void caculateJButtonMouseClicked(java.awt.event.MouseEvent evt) {
		double result = 0;
		//char strOperotor = operJTextField.getText().charAt(0);
		double numA = Double.parseDouble(numAJTextField.getText());
		double numB = Double.parseDouble(numBJTextField.getText());
		
		Operation oper ;//= new Operation(numA,numB);
		oper = OperationFactory.creatOperation(operJTextField.getText());
		oper.dNumberA = numA;
		oper.dNumberB = numB;
		result = oper.getResult();
		
		resultJLabel.setText(String.valueOf(result));
		// TODO add your handling code here:
	}//GEN-LAST:event_caculateJButtonMouseClicked

	//GEN-FIRST:event_clearJButtonMouseClicked
	private void clearJButtonMouseClicked(java.awt.event.MouseEvent evt) {
		numAJTextField.setText("");
		numBJTextField.setText("");
		resultJLabel.setText("");
		operJTextField.setText("");
	}//GEN-LAST:event_clearJButtonMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Caculator().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel answerJLabel;

	private javax.swing.JButton caculateJButton;

	private javax.swing.JButton clearJButton;

	private javax.swing.JTextField numAJTextField;

	private javax.swing.JLabel numAJlabel;

	private javax.swing.JTextField numBJTextField;

	private javax.swing.JLabel numBJlabel;

	private javax.swing.JTextField operJTextField;

	private javax.swing.JLabel resultJLabel;
	// End of variables declaration//GEN-END:variables

}